name: Security Scans

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Run Security Scans

    steps:
      - name: Checkout Infra Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Terrascan
        run: |
          echo "Downloading Terrascan..."
          curl -s https://api.github.com/repos/tenable/terrascan/releases/latest \
          | grep "browser_download_url.*linux_amd64.tar.gz" \
          | cut -d '"' -f 4 \
          | xargs curl -L -o terrascan.tar.gz
          tar -xzf terrascan.tar.gz
          sudo mv terrascan /usr/local/bin/
          terrascan version

      - name: Run Terrascan
        run: |
          echo "Scanning EKS Terraform infrastructure code..."
          terrascan scan -d ./eks-automode-pipeline
